using DotNetRestaurantManagement.Constants;
using DotNetRestaurantManagement.Helpers;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;

namespace RestrauntsManagement.Tests.Helpers
{
    [TestClass]
    public class PasswordHashingHelperTests
    {
        [TestMethod]
        [Description("Verifies that Hash returns a non-null and non-empty BCrypt password hash for a valid password.")]
        public void Hash_ValidPassword_ReturnsHash()
        {
            string password = "Vyakhya@123";
            string result = PasswordHashingHelper.Hash(password);
            result.Should().NotBeNullOrWhiteSpace();
        }

        [TestMethod]
        [Description("Verifies that Hash returns a BCrypt hash that is different from the original password.")]
        public void Hash_ValidPassword_DoesNotReturnOriginalPassword()
        {
            string password = "Vyakhya@123";
            string result = PasswordHashingHelper.Hash(password);
            result.Should().NotBe(password);
        }

        [TestMethod]
        [Description("Verifies that Hash generates different hashes for the same password because BCrypt uses a unique salt.")]
        public void Hash_SamePassword_GeneratesDifferentHashes()
        {
            string password = "Vyakhya@123";
            string firstHash = PasswordHashingHelper.Hash(password);
            string secondHash = PasswordHashingHelper.Hash(password);
            firstHash.Should().NotBe(secondHash);
        }

        [TestMethod]
        [Description("Verifies that Hash creates a hash that can be successfully verified against the original password.")]
        public void Hash_ValidPassword_CreatesVerifiableHash()
        {
            string password = "Vyakhya@123";
            string hash = PasswordHashingHelper.Hash(password);
            PasswordHashingHelper.Verify(password, hash).Should().BeTrue();
        }

        [TestMethod]
        [Description("Verifies that Verify returns true when the password matches the stored BCrypt hash.")]
        public void Verify_CorrectPassword_ReturnsTrue()
        {
            string password = "Vyakhya@123";
            string hash = PasswordHashingHelper.Hash(password);
            bool result = PasswordHashingHelper.Verify(password, hash);
            result.Should().BeTrue();
        }

        [TestMethod]
        [Description("Verifies that Verify returns false when the password does not match the stored BCrypt hash.")]
        public void Verify_IncorrectPassword_ReturnsFalse()
        {
            string password = "Vyakhya@123";
            string wrongPassword = "WrongPassword@123";
            string hash = PasswordHashingHelper.Hash(password);
            bool result = PasswordHashingHelper.Verify(wrongPassword, hash);
            result.Should().BeFalse();
        }

        [TestMethod]
        [Description("Verifies that Verify works correctly with a BCrypt hash generated by the helper.")]
        public void Verify_GeneratedHash_ReturnsTrue()
        {
            string password = "TestPassword@123";
            string hash = PasswordHashingHelper.Hash(password);
            bool result = PasswordHashingHelper.Verify(password, hash);
            result.Should().BeTrue();
        }
    }
}
